export type Locale = "en" | "ru" | "kk";

export const locales: Locale[] = ["kk", "en", "ru"];

const copy = {
  en: {
    brand: "iter",
    eyebrow: "Kazakhstan, Summer Work Travel",
    shapeFind: "FIND",
    shapeRead: "READ",
    shapeContact: "CONTACT",
    shapeFooter: "ITER DIRECTORY",
    heroGuide: "Explore the directory",
    navHow: "How it works",
    navTrust: "What to check",
    backToTop: "Back to top",
    viewDetails: "View details",
    footerExplore: "Explore",
    footerProject: "Project",
    sourceCode: "Source code on GitHub",
    manageOffers: "Manage offers",
    moreFilters: "More filters",
    stepFind: "Find a role",
    stepFindText:
      "Search the current season and narrow the details that matter to you.",
    stepCheck: "Check the details",
    stepCheckText:
      "Read the conditions, source, and separate trust facts on each vacancy.",
    stepContact: "Contact directly",
    stepContactText:
      "See the destination before opening the employer's own contact link.",
    trustHeading: "What we know",
    trustIntro:
      "Each vacancy shows its source and when the exact job was last confirmed.",
    trustFresh:
      "A confirmation older than 14 days removes a job from current results.",
    trustSponsor:
      "Employer identity, an open vacancy, a sponsor route, and sponsor approval are separate facts.",
    trustContact:
      "The directory does not submit an application or make a sponsor decision for you.",
    directory: "Summer jobs, with the details in view",
    intro:
      "Explore employer listings for a Summer Work Travel season. Read the conditions and evidence, then contact the employer yourself.",
    browse: "Browse vacancies",
    howItWorks: "Three steps",
    howText:
      "Listings are maintained by the directory. Employer contact opens outside this site. A listed job is not a sponsor decision or a job offer to you.",
    search: "Search jobs or employers",
    searchPlaceholder: "Role or employer",
    filters: "Filters",
    state: "State",
    city: "City",
    season: "Season",
    category: "Job type",
    startFrom: "Starts on or after",
    endBy: "Ends on or before",
    minPay: "Minimum pay",
    payBasis: "Pay basis",
    currency: "Currency",
    minHours: "Min. hours per week",
    housingKnown: "Housing information",
    housingAny: "Any",
    housingKnownOption: "Details provided",
    housingUnknownOption: "Not provided",
    freshness: "Last confirmed",
    freshnessAny: "Within 14 days",
    freshness7: "Within 7 days",
    freshness3: "Within 3 days",
    apply: "Show results",
    done: "Done",
    clear: "Clear filters",
    results: "Vacancies",
    noListings: "No current vacancies yet",
    noListingsText:
      "Check back after new employer confirmations are published.",
    noResults: "No vacancies match these filters",
    noResultsText: "Try widening dates, pay, hours, or location.",
    unavailable: "This vacancy is unavailable",
    stale: "This vacancy needs a new confirmation",
    staleText:
      "Its last employer confirmation has passed the 14-day window. It is no longer shown as current.",
    unavailableText:
      "It may be paused, closed, or past its confirmation window. Check current vacancies for other options.",
    missing: "Vacancy not found",
    missingText: "This link does not point to a published vacancy.",
    error: "Vacancies could not be loaded",
    invalidFilters: "Check the filter values",
    invalidFiltersText:
      "The dates or numeric conditions are invalid. Correct them and try again.",
    errorText:
      "Please try again later. No sample vacancies are shown as live results.",
    retry: "Try again",
    loading: "Loading vacancies",
    unknown: "Unknown",
    fromEmployer: "Employer source text, language not recorded",
    hour: "hour",
    day: "day",
    week: "week",
    month: "month",
    seasonBasis: "season",
    conditions: "Work conditions",
    evidence: "Evidence and status",
    employer: "Employer",
    role: "Role and duties",
    location: "Location",
    dates: "Work dates",
    pay: "Pay",
    hours: "Expected hours per week",
    housing: "Housing",
    housingCost: "Housing cost",
    transport: "Transport",
    source: "Official job source",
    evidenceSource: "Source",
    employerSite: "Employer website",
    timezone: "Local time zone",
    confirmed: "Vacancy confirmed on",
    identityChecked: "Employer identity checked",
    identityNotChecked: "Employer identity not checked",
    identityDisputed: "Employer identity disputed",
    routeReported: "Employer reports working with",
    routeReportedGeneric: "Employer reports a sponsor route",
    routeNone: "Employer reports no sponsor route",
    routeUnknown: "Sponsor route not reported",
    approvalUnknown: "Sponsor approval not confirmed",
    approvalPending: "Sponsor review pending",
    approvalConfirmed: "Sponsor approval confirmed by",
    approvalDenied: "Sponsor did not approve this job",
    directContact: "Contact employer directly",
    contactIntro: "You are leaving iter for this employer contact destination:",
    continue: "Continue to destination",
    channelWeb: "Contact page",
    channelEmail: "Email",
    channelPhone: "Phone",
    cancel: "Cancel",
    unsafeContact: "Contact link unavailable",
    external: "Opens an external destination",
    telegram: "Open in Telegram",
    back: "Back to vacancies",
    next: "Next page",
    previous: "Previous page",
    language: "Language",
    switchLanguage: "Switch language to {language}",
    skip: "Skip to main content",
    reviews: "Experiences",
    reviewsEmpty: "No approved experiences yet.",
    reviewCount: "Approved experiences",
    roleReview: "Role worked",
    reviewSubmit: "Share your experience",
    stepOf: "Step {n} of {total}",
    nextStep: "Next",
    stepBack: "Back",
    stepRole: "Your role",
    stepMatch: "Did the job match the listing?",
    stepStory: "Your experience",
    reviewHint:
      "Use a short factual account. Do not include names, contact details, documents, private messages, or accusations.",
    reviewMessage: "Optional experience (500 characters maximum)",
    reviewConsent:
      "I understand this is self-reported and will be checked before publication.",
    sendReview: "Send for review",
    reviewPending: "Received. Your experience is pending moderation.",
    report: "Report an issue",
    reportReason: "Reason",
    reportSubject: "What are you reporting?",
    reportListing: "This vacancy",
    reportReview: "Experience {n}: {role}, {date}",
    listingReasonClosed: "Vacancy is closed or filled",
    listingReasonInaccurate: "Wrong or outdated details",
    listingReasonSuspicious: "Suspicious employer or link",
    listingReasonPersonal: "Contains personal data",
    reviewReasonPersonal: "Names or contact details",
    reviewReasonFalse: "False or misleading",
    reviewReasonHarmful: "Offensive or threatening",
    reviewReasonOffTopic: "Not about this job",
    reportOther: "Other",
    reportExplanation: "Optional explanation (300 characters maximum)",
    sendReport: "Send report",
    reportReceived: "Report received. A moderator will review it.",
    submitError: "Could not send this. Please try again.",
    invalidFeedback:
      "Check the form. Free text cannot contain numbers, @, or links.",
    unknownReview: "Unknown",
    selfReported: "Self-reported experience; employment is not verified",
    matched: "Matched description",
    notMatched: "Did not match",
    notApplicable: "Not applicable",
    payReview: "Pay as described",
    payClarity: "Were pay terms clear?",
    payClear: "Clear",
    payUnclear: "Unclear",
    hoursReview: "Hours",
    housingReview: "Housing",
    transportReview: "Transport",
    demo: "Local demonstration data, not live vacancies",
    anyDate: "Any date",
    clearDate: "Clear date",
    calendarBack: "Back to filters",
    previousMonth: "Previous month",
    nextMonth: "Next month",
    rangeBoth: "{start} to {end}",
    rangeFrom: "From {start}",
    rangeUntil: "Until {end}",
    seasonYear: "Season {year}",
  },
  ru: {
    brand: "iter",
    eyebrow: "Казахстан, Summer Work Travel",
    shapeFind: "НАЙТИ",
    shapeRead: "ИЗУЧИТЬ",
    shapeContact: "СВЯЗАТЬСЯ",
    shapeFooter: "КАТАЛОГ ITER",
    heroGuide: "Разделы каталога",
    navHow: "Как это работает",
    navTrust: "Что проверить",
    backToTop: "Наверх",
    viewDetails: "Подробнее",
    footerExplore: "Разделы",
    footerProject: "Проект",
    sourceCode: "Исходный код на GitHub",
    manageOffers: "Управление предложениями",
    moreFilters: "Больше фильтров",
    stepFind: "Найдите вакансию",
    stepFindText: "Выберите сезон и условия, которые важны именно вам.",
    stepCheck: "Проверьте детали",
    stepCheckText:
      "Изучите условия, источник и отдельные статусы каждой вакансии.",
    stepContact: "Свяжитесь напрямую",
    stepContactText:
      "Перед переходом вы увидите, куда ведёт ссылка работодателя.",
    trustHeading: "Что известно",
    trustIntro:
      "У каждой вакансии указан источник и дата последнего подтверждения именно этой работы.",
    trustFresh:
      "Через 14 дней без нового подтверждения вакансия исчезает из актуальных результатов.",
    trustSponsor:
      "Проверка работодателя, открытая вакансия, маршрут через спонсора и одобрение спонсора являются разными фактами.",
    trustContact:
      "Каталог не подаёт заявку за вас и не принимает решения за спонсора.",
    directory: "Летняя работа: условия на виду",
    intro:
      "Изучайте вакансии работодателей для сезона Summer Work Travel. Проверьте условия и источники, затем свяжитесь с работодателем напрямую.",
    browse: "Смотреть вакансии",
    howItWorks: "Три шага",
    howText:
      "Каталог поддерживает объявления. Контакт с работодателем происходит вне сайта. Публикация не означает решение спонсора или предложение работы лично вам.",
    search: "Поиск по вакансии или работодателю",
    searchPlaceholder: "Должность или работодатель",
    filters: "Фильтры",
    state: "Штат",
    city: "Город",
    season: "Сезон",
    category: "Тип работы",
    startFrom: "Начало не раньше",
    endBy: "Окончание не позже",
    minPay: "Оплата от",
    payBasis: "За период",
    currency: "Валюта",
    minHours: "Часов в неделю, от",
    housingKnown: "Информация о жилье",
    housingAny: "Любая",
    housingKnownOption: "Условия указаны",
    housingUnknownOption: "Не указаны",
    freshness: "Последнее подтверждение",
    freshnessAny: "За 14 дней",
    freshness7: "За 7 дней",
    freshness3: "За 3 дня",
    apply: "Показать",
    done: "Готово",
    clear: "Сбросить фильтры",
    results: "Вакансии",
    noListings: "Пока нет актуальных вакансий",
    noListingsText:
      "Новые объявления появятся после подтверждения работодателем.",
    noResults: "По этим фильтрам вакансий нет",
    noResultsText: "Попробуйте расширить даты, оплату, часы или место.",
    unavailable: "Вакансия недоступна",
    stale: "Нужно новое подтверждение вакансии",
    staleText:
      "Последнее подтверждение работодателя старше 14 дней. Вакансия больше не показывается как актуальная.",
    unavailableText:
      "Она может быть приостановлена, закрыта или нуждаться в новом подтверждении. Посмотрите актуальные вакансии.",
    missing: "Вакансия не найдена",
    missingText: "Эта ссылка не ведёт на опубликованную вакансию.",
    error: "Не удалось загрузить вакансии",
    invalidFilters: "Проверьте значения фильтров",
    invalidFiltersText:
      "Даты или числа введены неверно. Исправьте их и попробуйте снова.",
    errorText:
      "Попробуйте позже. Тестовые вакансии не показываются как действующие.",
    retry: "Повторить",
    loading: "Загружаем вакансии",
    unknown: "Не указано",
    fromEmployer: "Исходный текст работодателя, язык не указан",
    hour: "час",
    day: "день",
    week: "неделю",
    month: "месяц",
    seasonBasis: "сезон",
    conditions: "Условия работы",
    evidence: "Источники и статусы",
    employer: "Работодатель",
    role: "Должность и задачи",
    location: "Место",
    dates: "Даты работы",
    pay: "Оплата",
    hours: "Ожидаемые часы в неделю",
    housing: "Жильё",
    housingCost: "Стоимость жилья",
    transport: "Транспорт",
    source: "Официальный источник вакансии",
    evidenceSource: "Источник",
    employerSite: "Сайт работодателя",
    timezone: "Местный часовой пояс",
    confirmed: "Вакансия подтверждена",
    identityChecked: "Личность работодателя проверена",
    identityNotChecked: "Личность работодателя не проверена",
    identityDisputed: "Данные о работодателе оспариваются",
    routeReported: "По словам работодателя, он работает с",
    routeReportedGeneric: "Работодатель сообщает о маршруте через спонсора",
    routeNone: "Работодатель сообщает, что маршрута через спонсора нет",
    routeUnknown: "Маршрут через спонсора не указан",
    approvalUnknown: "Одобрение спонсора не подтверждено",
    approvalPending: "Рассмотрение спонсором ожидается",
    approvalConfirmed: "Спонсор подтвердил вакансию:",
    approvalDenied: "Спонсор не одобрил вакансию",
    directContact: "Связаться с работодателем",
    contactIntro: "Вы перейдёте с iter по ссылке работодателя:",
    continue: "Открыть ссылку",
    channelWeb: "Страница для связи",
    channelEmail: "Эл. почта",
    channelPhone: "Телефон",
    cancel: "Отмена",
    unsafeContact: "Контактная ссылка недоступна",
    external: "Откроется внешний сайт",
    telegram: "Открыть в Telegram",
    back: "К вакансиям",
    next: "Следующая страница",
    previous: "Предыдущая страница",
    language: "Язык",
    switchLanguage: "Сменить язык на {language}",
    skip: "Перейти к содержимому",
    reviews: "Опыт участников",
    reviewsEmpty: "Пока нет одобренных отзывов.",
    reviewCount: "Одобренных отзывов",
    roleReview: "Кем вы работали",
    reviewSubmit: "Поделиться опытом",
    stepOf: "Шаг {n} из {total}",
    nextStep: "Далее",
    stepBack: "Назад",
    stepRole: "Ваша роль",
    stepMatch: "Совпали ли условия с описанием?",
    stepStory: "Ваш опыт",
    reviewHint:
      "Коротко опишите факты. Не указывайте имена, контакты, документы, личную переписку или обвинения.",
    reviewMessage: "Дополнение по желанию (до 500 символов)",
    reviewConsent:
      "Я понимаю, что это мой личный опыт и отзыв проверят перед публикацией.",
    sendReview: "Отправить на проверку",
    reviewPending: "Получено. Отзыв ожидает проверки.",
    report: "Сообщить о проблеме",
    reportReason: "Причина",
    reportSubject: "О чём вы сообщаете?",
    reportListing: "Эта вакансия",
    reportReview: "Отзыв {n}: {role}, {date}",
    listingReasonClosed: "Вакансия закрыта или занята",
    listingReasonInaccurate: "Неверные или устаревшие данные",
    listingReasonSuspicious: "Подозрительный работодатель или ссылка",
    listingReasonPersonal: "Содержит личные данные",
    reviewReasonPersonal: "Имена или контакты",
    reviewReasonFalse: "Ложный или вводящий в заблуждение",
    reviewReasonHarmful: "Оскорбления или угрозы",
    reviewReasonOffTopic: "Не об этой работе",
    reportOther: "Другое",
    reportExplanation: "Пояснение по желанию (до 300 символов)",
    sendReport: "Отправить сообщение",
    reportReceived: "Сообщение получено. Модератор его рассмотрит.",
    submitError: "Не удалось отправить. Попробуйте ещё раз.",
    invalidFeedback:
      "Проверьте форму. В тексте нельзя указывать цифры, @ или ссылки.",
    unknownReview: "Неизвестно",
    selfReported: "Опыт со слов автора; работа не подтверждена",
    matched: "Совпало с описанием",
    notMatched: "Не совпало",
    notApplicable: "Не применимо",
    payReview: "Оплата соответствовала описанию",
    payClarity: "Условия оплаты были понятны?",
    payClear: "Да, понятны",
    payUnclear: "Нет, непонятны",
    hoursReview: "Часы",
    housingReview: "Жильё",
    transportReview: "Транспорт",
    demo: "Локальные тестовые данные, не действующие вакансии",
    anyDate: "Любая дата",
    clearDate: "Сбросить дату",
    calendarBack: "К фильтрам",
    previousMonth: "Предыдущий месяц",
    nextMonth: "Следующий месяц",
    rangeBoth: "С {start} по {end}",
    rangeFrom: "С {start}",
    rangeUntil: "До {end}",
    seasonYear: "Сезон {year}",
  },
  kk: {
    brand: "iter",
    eyebrow: "Қазақстан, Summer Work Travel",
    shapeFind: "ТАБУ",
    shapeRead: "ОҚУ",
    shapeContact: "ХАБАРЛАСУ",
    shapeFooter: "ITER КАТАЛОГЫ",
    heroGuide: "Каталог бөлімдері",
    navHow: "Қалай жұмыс істейді",
    navTrust: "Нені тексеру керек",
    backToTop: "Жоғарыға",
    viewDetails: "Толығырақ",
    footerExplore: "Бөлімдер",
    footerProject: "Жоба",
    sourceCode: "GitHub-тағы бастапқы код",
    manageOffers: "Ұсыныстарды басқару",
    moreFilters: "Қосымша сүзгілер",
    stepFind: "Бос орынды табыңыз",
    stepFindText: "Маусымды және өзіңізге маңызды шарттарды таңдаңыз.",
    stepCheck: "Мәліметтерді тексеріңіз",
    stepCheckText:
      "Әр бос орынның шарттарын, дереккөзін және бөлек мәртебелерін қараңыз.",
    stepContact: "Тікелей хабарласыңыз",
    stepContactText:
      "Жұмыс берушінің сілтемесін ашпас бұрын оның қайда апаратынын көресіз.",
    trustHeading: "Не белгілі",
    trustIntro:
      "Әр бос орында дереккөз және дәл осы жұмыстың соңғы расталған күні көрсетіледі.",
    trustFresh:
      "14 күн ішінде қайта расталмаған бос орын қазіргі нәтижелерден алынады.",
    trustSponsor:
      "Жұмыс берушіні тексеру, ашық бос орын, демеуші бағыты және демеушінің мақұлдауы бөлек деректер.",
    trustContact:
      "Каталог сіздің атыңыздан өтініш бермейді және демеушінің орнына шешім қабылдамайды.",
    directory: "Жазғы жұмыс: шарттары анық көрсетілген",
    intro:
      "Summer Work Travel маусымына арналған жұмыс берушілердің бос орындарын қараңыз. Шарттары мен дереккөздерін тексеріп, жұмыс берушіге өзіңіз хабарласыңыз.",
    browse: "Бос орындарды қарау",
    howItWorks: "Үш қадам",
    howText:
      "Каталог хабарландыруларды жүргізеді. Жұмыс берушімен байланыс осы сайттан тыс жерде өтеді. Жарияланым демеушінің шешімі немесе сізге жасалған жұмыс ұсынысы емес.",
    search: "Жұмыс не жұмыс беруші бойынша іздеу",
    searchPlaceholder: "Лауазым немесе жұмыс беруші",
    filters: "Сүзгілер",
    state: "Штат",
    city: "Қала",
    season: "Маусым",
    category: "Жұмыс түрі",
    startFrom: "Басталуы (ең ерте)",
    endBy: "Аяқталуы (ең кеш)",
    minPay: "Ең төменгі ақы",
    payBasis: "Ақы кезеңі",
    currency: "Валюта",
    minHours: "Аптасына кемінде сағат",
    housingKnown: "Тұрғын үй туралы ақпарат",
    housingAny: "Барлығы",
    housingKnownOption: "Шарттары көрсетілген",
    housingUnknownOption: "Көрсетілмеген",
    freshness: "Соңғы растау",
    freshnessAny: "14 күн ішінде",
    freshness7: "7 күн ішінде",
    freshness3: "3 күн ішінде",
    apply: "Нәтижелерді көрсету",
    done: "Дайын",
    clear: "Сүзгілерді тазалау",
    results: "Бос орындар",
    noListings: "Әзірге қазіргі бос орындар жоқ",
    noListingsText:
      "Жаңа хабарландырулар жұмыс беруші растағаннан кейін шығады.",
    noResults: "Бұл сүзгілерге сай бос орын жоқ",
    noResultsText: "Күндерді, ақыны, сағатты немесе орынды кеңейтіп көріңіз.",
    unavailable: "Бұл бос орын қолжетімсіз",
    stale: "Бос орынды қайта растау қажет",
    staleText:
      "Жұмыс берушінің соңғы растауынан 14 күн өтті. Бос орын енді қазіргі ұсыныс ретінде көрсетілмейді.",
    unavailableText:
      "Ол тоқтатылған, жабылған немесе қайта растауды қажет етуі мүмкін. Қазіргі бос орындарды қараңыз.",
    missing: "Бос орын табылмады",
    missingText: "Бұл сілтеме жарияланған бос орынға апармайды.",
    error: "Бос орындарды жүктеу мүмкін болмады",
    invalidFilters: "Сүзгі мәндерін тексеріңіз",
    invalidFiltersText:
      "Күндер немесе сандар қате енгізілген. Түзетіп, қайталап көріңіз.",
    errorText:
      "Кейінірек қайталап көріңіз. Сынақ деректері нақты бос орын ретінде көрсетілмейді.",
    retry: "Қайталау",
    loading: "Бос орындар жүктелуде",
    unknown: "Көрсетілмеген",
    fromEmployer: "Жұмыс берушінің бастапқы мәтіні, тілі көрсетілмеген",
    hour: "сағат",
    day: "күн",
    week: "апта",
    month: "ай",
    seasonBasis: "маусым",
    conditions: "Жұмыс шарттары",
    evidence: "Дереккөздер мен мәртебелер",
    employer: "Жұмыс беруші",
    role: "Лауазым мен міндеттер",
    location: "Орналасқан жері",
    dates: "Жұмыс күндері",
    pay: "Ақы",
    hours: "Аптасына күтілетін сағат",
    housing: "Тұрғын үй",
    housingCost: "Тұрғын үй құны",
    transport: "Көлік",
    source: "Бос орынның ресми дереккөзі",
    evidenceSource: "Дереккөз",
    employerSite: "Жұмыс берушінің сайты",
    timezone: "Жергілікті уақыт белдеуі",
    confirmed: "Бос орын расталған күн",
    identityChecked: "Жұмыс берушінің деректері тексерілген",
    identityNotChecked: "Жұмыс берушінің деректері тексерілмеген",
    identityDisputed: "Жұмыс беруші туралы деректер даулы",
    routeReported: "Жұмыс берушінің айтуынша, ол жұмыс істейді:",
    routeReportedGeneric: "Жұмыс беруші демеуші бағыты барын хабарлайды",
    routeNone: "Жұмыс беруші демеуші бағыты жоқ екенін хабарлайды",
    routeUnknown: "Демеуші бағыты көрсетілмеген",
    approvalUnknown: "Демеушінің мақұлдауы расталмаған",
    approvalPending: "Демеушінің қарауы күтілуде",
    approvalConfirmed: "Демеуші бос орынды мақұлдаған:",
    approvalDenied: "Демеуші бос орынды мақұлдамады",
    directContact: "Жұмыс берушіге хабарласу",
    contactIntro: "iter сайтынан жұмыс берушінің мына сілтемесіне өтесіз:",
    continue: "Сілтемені ашу",
    channelWeb: "Байланыс беті",
    channelEmail: "Электрондық пошта",
    channelPhone: "Телефон",
    cancel: "Бас тарту",
    unsafeContact: "Байланыс сілтемесі қолжетімсіз",
    external: "Сыртқы сайт ашылады",
    telegram: "Telegram-да ашу",
    back: "Бос орындарға қайту",
    next: "Келесі бет",
    previous: "Алдыңғы бет",
    language: "Тіл",
    switchLanguage: "Тілді ауыстыру: {language}",
    skip: "Негізгі мазмұнға өту",
    reviews: "Қатысушылар тәжірибесі",
    reviewsEmpty: "Әзірге мақұлданған пікір жоқ.",
    reviewCount: "Мақұлданған пікірлер",
    roleReview: "Атқарған жұмысыңыз",
    reviewSubmit: "Тәжірибеңізбен бөлісіңіз",
    stepOf: "{n}-қадам, барлығы {total}",
    nextStep: "Келесі",
    stepBack: "Артқа",
    stepRole: "Сіздің рөліңіз",
    stepMatch: "Шарттар сипаттамаға сәйкес келді ме?",
    stepStory: "Тәжірибеңіз",
    reviewHint:
      "Қысқа әрі нақты жазыңыз. Адам аттарын, байланыс деректерін, құжаттарды, жеке хаттарды немесе айыптауларды қоспаңыз.",
    reviewMessage: "Қосымша пікір (ең көбі 500 таңба)",
    reviewConsent:
      "Бұл менің жеке тәжірибем екенін және пікір жарияланар алдында тексерілетінін түсінемін.",
    sendReview: "Тексеруге жіберу",
    reviewPending: "Алынды. Пікір модерацияны күтуде.",
    report: "Мәселе туралы хабарлау",
    reportReason: "Себебі",
    reportSubject: "Не туралы хабарлайсыз?",
    reportListing: "Осы бос орын",
    reportReview: "{n}-пікір: {role}, {date}",
    listingReasonClosed: "Бос орын жабылған немесе толған",
    listingReasonInaccurate: "Қате немесе ескірген мәліметтер",
    listingReasonSuspicious: "Күдікті жұмыс беруші немесе сілтеме",
    listingReasonPersonal: "Жеке деректер бар",
    reviewReasonPersonal: "Аттар немесе байланыс деректері",
    reviewReasonFalse: "Жалған немесе адастыратын",
    reviewReasonHarmful: "Қорлау немесе қорқыту",
    reviewReasonOffTopic: "Бұл жұмыс туралы емес",
    reportOther: "Басқа",
    reportExplanation: "Қосымша түсіндірме (ең көбі 300 таңба)",
    sendReport: "Хабарлама жіберу",
    reportReceived: "Хабарлама алынды. Модератор оны қарайды.",
    submitError: "Жіберілмеді. Қайта көріңіз.",
    invalidFeedback:
      "Нысанды тексеріңіз. Мәтінде сан, @ немесе сілтеме болмауы керек.",
    unknownReview: "Белгісіз",
    selfReported: "Автордың айтуына негізделген; жұмыс істегені расталмаған",
    matched: "Сипаттамаға сай болды",
    notMatched: "Сай болмады",
    notApplicable: "Қатысты емес",
    payReview: "Ақы сипаттамаға сай болды",
    payClarity: "Төлем шарттары түсінікті болды ма?",
    payClear: "Иә, түсінікті",
    payUnclear: "Жоқ, түсініксіз",
    hoursReview: "Сағат",
    housingReview: "Тұрғын үй",
    transportReview: "Көлік",
    demo: "Жергілікті сынақ деректері, нақты бос орындар емес",
    anyDate: "Кез келген күн",
    clearDate: "Күнді тазалау",
    calendarBack: "Сүзгілерге оралу",
    previousMonth: "Алдыңғы ай",
    nextMonth: "Келесі ай",
    rangeBoth: "{start} бастап {end} дейін",
    rangeFrom: "{start} бастап",
    rangeUntil: "{end} дейін",
    seasonYear: "{year} маусымы",
  },
} as const;

export type Copy = { [Key in keyof (typeof copy)["en"]]: string };
export function getCopy(locale: Locale): Copy {
  return copy[locale];
}

export function isLocale(value: string): value is Locale {
  return value === "en" || value === "ru" || value === "kk";
}

export function intlLocale(locale: Locale): string {
  return locale === "kk" ? "kk-KZ" : locale === "ru" ? "ru-RU" : "en-US";
}

export function fill(
  template: string,
  values: Record<string, string | number>,
) {
  return template.replace(/\{(\w+)\}/g, (_, key: string) =>
    String(values[key] ?? ""),
  );
}

export function localePath(locale: Locale, path = "/"): string {
  const prefix = locale === "en" ? "" : `/${locale}`;
  return `${prefix}${path}`;
}
